spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&charsetEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!@

  mail:
    host: smtp.gmail.com
    port: 587
    username: jinyngg@gmail.com
    password: ebfrmjupncqpfgcu
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    show-sql: true
    database: mysql

  sql:
    init:
      mode: always

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081